package com.parley.parley.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import javax.persistence.*;
import java.util.List;
import java.util.UUID;

@Entity
@DynamoDBTable(tableName = "instructors")
public class Instructor {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    UUID id;

    String firstname;
    String lastname;
    String email;

    @Column(unique = true)
    String username;
    String password;

    List<String> classes;


    //getters

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    @DynamoDBHashKey
    public String getFirstname() {
        return firstname;
    }

    @DynamoDBHashKey
    public String getLastname() {
        return lastname;
    }

    @DynamoDBHashKey
    public String getEmail() {
        return email;
    }

    @DynamoDBHashKey
    public String getUsername() {
        return username;
    }

    @DynamoDBHashKey
    public String getPassword() {
        return password;
    }

    @DynamoDBHashKey
    public List<String> getClasses() {
        return classes;
    }


    //setters

    public void setId(UUID id) {
        this.id = id;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setClasses(List<String> classes) {
        this.classes = classes;
    }
}
