package com.parley.parley.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.util.UUID;

@DynamoDBTable(tableName = "prompts")
public class Prompts {

    private UUID id;
    private String title;
    private String category;
    private String promptUrl;

    //Default Constructor
    public Prompts() {}

    public Prompts(String title,
                   String category,
                   String promptUrl) {
        this.setTitle(title);
        this.setCategory(category);
        this.setPromptUrl(promptUrl);
    }

    // Getters
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return this.id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return this.title;
    }

    @DynamoDBAttribute
    public String getCategory() {
        return this.category;
    }

    @DynamoDBAttribute
    public String getPromptUrl() {
        return this.promptUrl;
    }

    // Setters
    public void setId(UUID id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public void setPromptUrl(String promptUrl) {
        this.promptUrl = promptUrl;
    }
}
