package com.parley.parley.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
import java.util.UUID;

@DynamoDBTable(tableName = "schedules")
public class Schedules {

    UUID id;
    UUID studentOne;
    UUID promptOne;
    UUID studentTwo;
    UUID promptTwo;
    @DateTimeFormat(pattern = "yyyy-mm-dd")
    Date dueDateOfInterview;

        //Default Constructor
        public Schedules() {}

        // Getters
        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        public UUID getId() {
            return id;
        }

        @DynamoDBAttribute
        public UUID getStudentOne() {
            return studentOne;
        }

        @DynamoDBAttribute
        public UUID getPromptOne() {
            return promptOne;
        }

        @DynamoDBAttribute
        public UUID getStudentTwo() {
            return studentTwo;
        }

        @DynamoDBAttribute
        public UUID getPromptTwo() {
            return promptTwo;
        }

        @DynamoDBAttribute
        public Date getDueDateOfInterview() {
            return dueDateOfInterview;
        }

        // Setters

        public void setId(UUID id) {
            this.id = id;
        }

        public void setStudentOne(UUID studentOne) {
            this.studentOne = studentOne;
        }

        public void setPromptOne(UUID promptOne) {
            this.promptOne = promptOne;
        }

        public void setStudentTwo(UUID studentTwo) {
            this.studentTwo = studentTwo;
        }

        public void setPromptTwo(UUID promptTwo) {
            this.promptTwo = promptTwo;
        }

        public void setDueDateOfInterview(Date dueDateOfInterview) {
            this.dueDateOfInterview = dueDateOfInterview;
        }
}
